import { categories as categoryObjects } from "@/app/page";

export const areasAtuacao = [
  "Entrega",
  "Retirada",
  "Entrega e Retirada",
  "Atendimento no Local",
  "Atendimento Online",
  "Atendimento Domiciliar",
  "Atendo todos os bairros de Saquarema",
  "Água Branca",
  "Alvorada",
  "Areal",
  "Asfalto Velho",
  "Aterrado",
  "Bacaxá",
  "Barra Nova",
  "Barreira",
  "Basiléa",
  "Bicuíba",
  "Bonsucesso",
  "Boqueirão",
  "Caixa d'Água",
  "Centro (Saquarema)",
  "Condado de Bacaxá",
  "Coqueiral",
  "Bairro de Fátima",
  "Engenho Grande",
  "Gravatá",
  "Guarani",
  "Ipitangas",
  "Itaúna",
  "Jaconé",
  "Jardim",
  "Jardim Ipitangas",
  "Leigos",
  "Madressilva",
  "Mombaça",
  "Morro dos Pregos",
  "Palmital",
  "Parque Marina",
  "Porto da Roça I",
  "Porto da Roça II",
  "Porto Novo",
  "Raia",
  "Retiro",
  "Rio d'Areia",
  "Rio Mole",
  "Sampaio Correia",
  "São Geraldo",
  "Serra de Mato Grosso",
  "Tinguí",
  "Verde Vale",
  "Vilatur",
  "Outro município",
];
export const categorias = categoryObjects.map((cat) => cat.title);

export const tagsPorCategoria: { [key: string]: string[] } = {
  "Artesanato e Criação Manual": [
    "Feito a Mão",
    "Peça Única",
    "Decoração",
    "Personalizado",
    "Presentes",
    "Crochê",
    "Biju",
    "Cerâmica",
    "Madeira",
    "Sustentável",
  ],
  "Beleza, Moda e Estética": [
    "Manicure",
    "Cabelo",
    "Maquiagem",
    "Roupas",
    "Acessórios",
    "Depilação",
    "Massagem",
    "Estética Facial",
    "Sobrancelha",
    "Cosméticos Naturais",
  ],
  "Comércio Local e Vendas": [
    "Entrega Rápida",
    "Loja Online",
    "Revendedor",
    "Produtos Importados",
    "Eletrônicos",
    "Materiais",
    "Varejo",
    "Atacado",
    "Promoção",
    "Frete Grátis",
  ],
  "Construção, Reforma e Manutenção": [
    "Eletricista",
    "Encanador",
    "Pintor",
    "Pedreiro",
    "Jardinagem",
    "Montador de Móveis",
    "Reparos",
    "Orçamento Grátis",
    "Piso",
    "Reforma de Casa",
  ],
  "Festas e Eventos": [
    "Decoração",
    "Buffet",
    "Fotografia",
    "Aniversário",
    "Casamento",
    "Música ao Vivo",
    "Aluguel de Mesas",
    "Recreação Infantil",
    "Eventos Corporativos",
    "Churrasco",
  ],
  "Gastronomia e Alimentação": [
    "Bolo",
    "Doces",
    "Comida Caseira",
    "Marmitex",
    "Delivery",
    "Salgados",
    "Vegetariano",
    "Vegano",
    "Cerveja Artesanal",
    "Petiscos",
  ],
  "Saúde, Bem-estar e Fitness": [
    "Personal Trainer",
    "Yoga",
    "Nutricionista",
    "Psicólogo",
    "Fisioterapia",
    "Medicina Natural",
    "Acupuntura",
    "Suplementos",
    "Aulas Online",
    "Espaço Zen",
  ],
  "Serviços Administrativos e Apoio": [
    "Contabilidade",
    "Consultoria",
    "Secretariado",
    "Digitalização",
    "Tradução",
    "Assessoria",
    "Finanças",
    "Currículo",
    "Escrita",
    "Organização",
  ],
  "Serviços Automotivos e Reparos": [
    "Mecânica",
    "Elétrica",
    "Borracharia",
    "Lava Jato",
    "Funilaria",
    "Guincho",
    "Revisão",
    "Pneu",
    "Motores",
    "Acessórios Automotivos",
  ],
  "Tecnologia e Serviços Digitais": [
    "Web Design",
    "Marketing Digital",
    "Redes Sociais",
    "Programação",
    "Manutenção PC",
    "Hospedagem",
    "Apps",
    "Consultoria TI",
    "SEO",
    "Criação de Vídeos",
  ],
  "Turismo, Cultura e Lazer": [
    "Guia Turístico",
    "Passeios",
    "Praia",
    "Hospedagem",
    "Aluguel de Bike",
    "Artesanato Local",
    "Aulas de Surf",
    "Trilhas",
    "Pousada",
    "Viagens",
  ],
  "Produtores Rurais e Atividades Agrícolas": [
    "Produtos Orgânicos",
    "Horta",
    "Feira Livre",
    "Frutas",
    "Vegetais",
    "Mel",
    "Gado",
    "Plantas Ornamentais",
    "Leite Fresco",
    "Ovos Caipiras",
  ],
};
export const canaisDeVendaOpcoes = [
  {
    label: "Redes Sociais (Instagram, Facebook, WhatsApp)",
    value: "Redes Sociais",
  },
  {
    label: "Marketplaces (Mercado Livre, Shopee, Amazon, etc.)",
    value: "Marketplaces",
  },
  {
    label: "Plataformas de serviços (GetNinjas, Workana, etc.)",
    value: "Plataformas de serviços",
  },
  {
    label: "Feiras e eventos (artesanato, gastronômicas, etc.)",
    value: "Feiras e eventos",
  },
  { label: "Loja própria / ponto fixo", value: "Loja própria / ponto fixo" },
  { label: "Atendimento em domicílio", value: "Atendimento em domicílio" },
  { label: "Boca a boca (recomendação)", value: "Boca a boca" },
  { label: "Outra forma", value: "Outra forma" },
];

export const campoLabels: { [key: string]: string } = {
  nome_responsavel: "Nome Completo do Responsável",
  cpf_responsavel: "CPF do Responsável",
  emailEstabelecimento: "E-mail de Contato Principal",

  // Seção "Informações do Negócio"
  nomeFantasia: "Nome Fantasia",
  cnpj: "CNPJ",
  categoria: "Categoria Principal",
  ccmei: "Certificado CCMEI",
  tagsInvisiveis: "Tags de Busca Sugeridas",
  cnae: "CNAE (Atividade Principal)",
  venda: "Canais de Venda",
  escala: "Avaliação de Impacto (Escala)",

  // Seção "Contato e Localização"
  contatoEstabelecimento: "Telefone / WhatsApp do Estabelecimento",
  endereco: "Endereço Físico do estabelecimento (se houver)",
  areasAtuacao: "Áreas de Atuação",

  // Seção "Detalhes e Mídia"
  descricao: "Descrição do seu Serviço/Produto",
  descricaoDiferencial: "Qual o seu diferencial?",
  website: "Website (Opcional)",
  instagram: "Instagram (Opcional)",
  logo: "Sua Logo",
  produtos: "Imagens do seu Produto ou Serviço",

  // Seção Final
  confirmacao: "Confirmação de Veracidade e LGPD",
};
